
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zvlspmzclzghfuuelyjq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp2bHNwbXpjbHpnaGZ1dWVseWpxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIwMTE1MDksImV4cCI6MjA1NzU4NzUwOX0.HkWoWlL9l06R7rtIbYXgxGAQXE93fP4ES1EzWnE7UF8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
